import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Thuy",
      email: "abc@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Mai",
      email: "amai@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Peach Doggy",
      category: "Squish",
      image: "/images/p1.png",
      price: 120,
      countInStock: 10,
      brand: "LV",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Blue Dino",
      category: "Squish",
      image: "/images/p2.png",
      price: 120,
      countInStock: 20,
      brand: "LV",
      rating: 4,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Purple Octopus",
      category: "Squish",
      image: "/images/p3.png",
      price: 120,
      countInStock: 0,
      brand: "LV",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Avocado",
      category: "Squish",
      image: "/images/p4.png",
      price: 110,
      countInStock: 10,
      brand: "LV",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Baby Shark",
      category: "Squish",
      image: "/images/p5.png",
      price: 120,
      countInStock: 5,
      brand: "LV",
      rating: 5,
      numReviews: 20,
      description: "high quality product",
    },
    {
      name: "Hello Kitty",
      category: "Squish",
      image: "/images/p6.png",
      price: 150,
      countInStock: 0,
      brand: "LV",
      rating: 4,
      numReviews: 18,
      description: "high quality product",
    },
  ],
};

export default data;
