const data = {
  products: [
    {
      _id: "1",
      name: "Peach Doggy",
      category: "Squish",
      image: "/images/p1.png",
      price: 120,
      countInStock: 10,
      brand: "LV",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Blue Dino",
      category: "Squish",
      image: "/images/p2.png",
      price: 120,
      countInStock: 20,
      brand: "LV",
      rating: 4,
      numReviews: 15,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Purple Octopus",
      category: "Squish",
      image: "/images/p3.png",
      price: 120,
      countInStock: 0,
      brand: "LV",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Avocado",
      category: "Squish",
      image: "/images/p4.png",
      price: 110,
      countInStock: 10,
      brand: "LV",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Baby Shark",
      category: "Squish",
      image: "/images/p5.png",
      price: 120,
      countInStock: 5,
      brand: "LV",
      rating: 5,
      numReviews: 20,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Hello Kitty",
      category: "Squish",
      image: "/images/p6.png",
      price: 150,
      countInStock: 0,
      brand: "LV",
      rating: 4,
      numReviews: 18,
      description: "high quality product",
    },
  ],
};

export default data;
